title: The Metrics Investor
description: Discover data-driven investment strategies with The Metrics Investor. Follow our journey as we use a custom stock screener to build a high-growth portfolio with consistent monthly updates and actionable insights.
remote_theme: pages-themes/minimal # Remove versioning for simplicity
url: http://themetricsinvestor.buckeltag.com
baseurl: ""
plugins:
  - jekyll-remote-theme
