title: The Metrics Investor
description: >-
  Discover data-driven investment strategies with The Metrics Investor. Follow our journey as we use a custom stock screener to build a high-growth portfolio with consistent monthly updates and actionable insights.
theme: pages-themes/minimal@v0.2.0
url: https://themetricsinvestor.buckeltag.com
baseurl: ""
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one